const double pricePerSmall = 25;
const double pricePerLarge = 35;
const double taxRate = 0.06;
const int estimateValidity = 30;
Console.WriteLine("Estimate for carpet cleaning service");
Console.WriteLine("---------------------------------");
Console.Write("Enter number of small carpets: ");
int smallCarpets = Convert.ToInt32(Console.ReadLine());
Console.Write("Enter number of large carpets: ");
int largeCarpets = Convert.ToInt32(Console.ReadLine());
double costSmall = smallCarpets * pricePerSmall;
double costLarge = largeCarpets * pricePerLarge;
double totalCost = costSmall + costLarge;
double tax = totalCost * taxRate;
double totalEstimate = totalCost + tax;
Console.WriteLine("\nEstimate for carpet cleaning service");
Console.WriteLine($"Number of small carpets: {smallCarpets}");
Console.WriteLine($"Number of large carpets: {largeCarpets}");
Console.WriteLine($"Price per small carpet: ${pricePerSmall}");
Console.WriteLine($"Price per large carpet: ${pricePerLarge}");
Console.WriteLine($"Cost: ${totalCost}");
Console.WriteLine($"Tax: ${tax}");
Console.WriteLine("====================================");
Console.WriteLine($"Total estimate: ${totalEstimate}");
Console.WriteLine($"This estimate is valid for {estimateValidity} days");